// <auto-generated />
using System;
using CodeSync.Execution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSync.Execution.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    partial class ExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSync.Execution.Models.ExecutionJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MemoryUsedKb")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("QUEUED");

                    b.Property<string>("Stderr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stdin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stdout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("Language");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ExecutionJobs");
                });

            modelBuilder.Entity("CodeSync.Execution.Models.SupportedLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RunCommand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("SupportedLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileExtension = ".py",
                            IsEnabled = true,
                            Name = "python",
                            RunCommand = "python3 {file}",
                            Version = "3.11"
                        },
                        new
                        {
                            Id = 2,
                            FileExtension = ".js",
                            IsEnabled = true,
                            Name = "javascript",
                            RunCommand = "node {file}",
                            Version = "Node.js 20"
                        },
                        new
                        {
                            Id = 3,
                            FileExtension = ".java",
                            IsEnabled = true,
                            Name = "java",
                            RunCommand = "javac {file} && java Main",
                            Version = "21"
                        },
                        new
                        {
                            Id = 4,
                            FileExtension = ".cs",
                            IsEnabled = true,
                            Name = "csharp",
                            RunCommand = "dotnet script {file}",
                            Version = ".NET 8"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
